### PR TITLE
made the navbar responsive for mobile devices

### PR DESCRIPTION
**Pull request by Amanuel-1**
if worked as planned, this pr will fix the issue #128 for the landing page.

### CODE REVIEW

**Comment by Bekacru** [comment]
Screenshot 2023-09-05 at 9 19 09 AM
Screenshot 2023-09-05 at 9 20 20 AM

**Comment by Bekacru** [comment]
> Screenshot 2023-09-05 at 9 19 09 AM Screenshot 2023-09-05 at 9 20 20 AM

I was thnking something more like this

**Comment by Amanuel-1** [comment]
sure . i'm on it

**Comment by Bekacru** [comment]
Hey, great work. Couple of things. 
1. You shound't use .react-email folder. It's protected folder for react email. So don't put the humberger menu there.
2. Use this hamburger icon from lucide icons https://lucide.dev/icons/menu Lucide is alredy installed on the project you just need to import it. And if you can add the hamburger menu in the icons file first.
3. You changed filesnot realted to ur current specially the .env.example remove all changes from ur commit you doesn't related with your commit. Including pnpm lock changes

**Comment by Amanuel-1** [comment]
i used div elements just to give it a smooth animation .

**Pull request closed without merging**
